baseURL: 'https://hcrudolph.com/'
languageCode: 'en-us'
title: 'Hans Christian Rudolph'
theme: 'PaperMod'
params:
  author: 'Hans Christian Rudolph'
  defaultTheme: light
  disableThemeToggle: true
  paginate: 10
  profileMode:
    enabled: true
    title: "Hi there 👋"
    subtitle: "I'm Hans, a cyber security professional specializing in wireless communications, network security, and related technologies. I'm based in Tokyo and currently work as a Senior Manager at Deloitte Cyber. Occasionally, I write about Japan and security."
    imageUrl: "images/photo.jpg"
    imageWidth: 150
    imageHeight: 150
  socialIcons:
    - name: "linkedin"
      url: "https://linkedin.com/in/hcrudolph"
    - name: "github"
      url: "https://github.com/hcrudolph"
menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
deployment:
  targets:
    name: "production"
    URL: "s3://staticpage-hcrudolph-com?region=eu-central-1"
    matchers:
      - pattern: "^.+\\.(png|jpg|gif)$"
        cacheControl: "max-age=31536000, no-transform, public"
        gzip: false
      - pattern: "^.+\\.(js|css|svg|ttf)$"
        cacheControl: "max-age=31536000, no-transform, public"
        gzip: true
      - pattern: "^sitemap\\.xml$"
        contentType: "application/xml"
        gzip: true
      - pattern: "^.+\\.(html|xml|json)$"
        gzip: true
